services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api-base
    build:
      target: development
    container_name: cat_dev_api
    ports:
      - "${API_PORT:-8003}:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - cat-dev-network
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    container_name: cat_dev_postgres
    networks:
      - cat-dev-network
    env_file:
      - .env
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: cat_dev_pgadmin
    networks:
      - cat-dev-network
    ports:
      - "127.0.0.1:5050:80"
    env_file:
      - .env
    depends_on:
      - postgres

networks:
  cat-dev-network:

volumes:
  postgres_dev_data:
