services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    container_name: cat_dev

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.test:/app/.env.test
    env_file:
      - .env
    environment:
      - IN_DOCKER=1

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

    command: npm run dev

  postgres:
    image: postgres:17-alpine
    container_name: cat_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongdevpass123
      - POSTGRES_DB=cat_dev
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4
    container_name: cat_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
volumes:
  postgres_data: