services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api-base
    build:
      target: test
    container_name: cat_test_api
    restart: no #Run the tests, print the results, and then let the container rest.
    ports:
      - "8001:8000"
    networks:
      - cat-test-network
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run test

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    container_name: cat_test_postgres
    networks:
      - cat-test-network
    env_file:
      - .env.test
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cat_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4
    container_name: cat_test_pgadmin
    networks:
      - cat-test-network
    ports:
      - "127.0.0.1:5051:80"
    env_file:
      - .env.test
    depends_on:
      - postgres

networks:
  cat-test-network:

volumes:
  postgres_test_data:
  test_app_src:
