import request from "supertest";
import app from "../servers/app.js";
import {afterAll, beforeAll, describe, expect, it} from "@jest/globals";
import {follows, posts, socials, users} from "../db/schema/index.js";
import {db, sql} from "../db/client.js";
import {eq, or} from "drizzle-orm";

describe("Profile Integration Suite with Live Test DB", ()=>{
    const testUsername = "kubra_test";
    let testUserId;
    let followerUserId;

    // Setup phase: Clean up previous data and insert mock records honoring all PG constraints
    beforeAll(async () =>{
        // Clean up table rows from previous runs safely using the unique username index
        await db.delete(socials).where(eq(socials.socialUrl, `https://youtube.com/${testUsername}`));
        await db.delete(users).where(or(eq(users.username, testUsername), eq(users.username, "follower_test")))

        // Insert the root user matching the auth.repository logic
        const [insertedUser]= await db.insert(users).values({
            name: "Kubra Korkmaz",
            username: testUsername,
            hashedPassword: "secure_mock_hash",
            email:"kubra@example.com",
            about: "Full-Stack Software Developer",
            profileImage: "profile.png",
            backgroundImage: "bg.png"
        }).returning();

        testUserId = insertedUser.id; // Capture the real integer ID generated by the DB

        // Insert a secondary user to test follow connections safely
        const [insertedFollower] = await db.insert(users).values({
            name: "Follower Friend",
            username: "follower_test",
            email: "follower@example.com",
            hashedPassword: "secure_mock_hash"
        }).returning();

        followerUserId = insertedFollower.id;

        // Insert dependent relational data matching your profile.repository layout
        await db.insert(socials).values({
            userId: testUserId,
            socialMedia: "youtube",
            socialUrl: `https://youtube.com/${testUsername}`
        });

        await db.insert(posts).values({
            userId: testUserId,
            type: "text",
            header: "First Tea Post",
            content: "Welcome to my support page!",
            donationSum: 50
        });

        // Establish an authentic follow record
        await db.insert(follows).values({
            followerId: followerUserId,
            followingId: testUserId
        });
    });

    // Teardown phase: Cascading deletes via references clear everything cleanly
    afterAll(async () =>{
        try {
            // Using strict checks to satisfy ESLint eqeqeq while guarding against undefined/null
            const conditions = [];
            if (testUserId !== undefined && testUserId !== null) {
                conditions.push(eq(users.id, testUserId));
            }
            if (followerUserId !== undefined && followerUserId !== null) {
                conditions.push(eq(users.id, followerUserId));
            }
            if (conditions.length > 0) {
                const predicate = conditions.length === 2 ? or(...conditions) : conditions[0];
                await db.delete(users).where(predicate);
            }
        } finally {
            // Safely terminate the open TCP sockets pool
            // Wrapping this in a finally block guarantees the socket closes even if a query breaks.
            if (sql && typeof sql.end === "function") {
                await sql.end();
            }
        }
    });

    // --- TEST SUITE FOR USER PANEL ---
    describe( "GET /api/v1/profile", ()=>{
        it("should resolve HTTP 200 and serve the matched panel information block", async () => {
            const res = await request(app)
                .get("/api/v1/profile")
                .query({username: testUsername});

            expect(res.status).toBe(200);
            expect(res.body).toEqual({
                id: testUserId,
                name: "Kubra Korkmaz",
                username: testUsername,
                profileImage: "profile.png",
                backgroundImage: "bg.png"
            });
        });
        it("should validate missing inputs and return HTTP 400 Bad Request", async () => {
            const res = await request(app).get("/api/v1/profile") // No query parameters

            expect(res.status).toBe(400);
            expect(res.body.message).toContain("Username query parameter is mandatory");
        });
    });

    // --- TEST SUITE FOR USER INTRO DASHBOARD ---
    describe("GET /api/v1/profile/intro", () => {
        it("should resolve HTTP 200 and combine socials, earnings, and connections", async ()=>{
            // Act: Fire the HTTP integrations query hitting your real controllers
            const res = await request(app)
                .get("/api/v1/profile/intro")
                .query({ username: testUsername, earningTimeline: 30 }) // or however your controller expects the lookup key (query, params, or session context)

            // Assert: Verify structural values returned straight out of PG
            expect(res.status).toBe(200);
            // Validate structural fields matched to your getIntroDashboard service mapper
            expect(res.body.about).toBe("Full-Stack Software Developer");
            expect(res.body.earningsTotal).toBe(50);

            expect(Array.isArray(res.body.socials)).toBe(true);
            expect(res.body.socials[0].socialMedia).toBe("youtube");

            expect(Array.isArray(res.body.topSupportedPosts)).toBe(true);
            expect(res.body.topSupportedPosts[0].header).toBe("First Tea Post");

            expect(Array.isArray(res.body.recentConnections)).toBe(true);
            expect(res.body.recentConnections[0].username).toBe("follower_test");
        });
    });


})